version: "3.9"

services:
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph:latest
    container_name: oxigraph
    command: serve --location /data --bind 0.0.0.0:7878 --cors
    ports:
      - "7878:7878"
    # volumes:
    #   - ./oxigraph-data:/data
    restart: unless-stopped

  hamburg_client:
    container_name: hamburg_client
    build: ./pipeline_hamburg
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - proxy_to_host
      - oxigraph
    environment:
      - DEBUG=*
    extra_hosts:
      - "localhost:host-gateway"
  
  telraam_client:
    container_name: telraam_client
    build: ./pipeline_telraam
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - oxigraph
      - proxy_to_host
    environment:
      - DEBUG=*
    extra_hosts:
      - "localhost:host-gateway"

  proxy_to_host:
    image: alpine/socat
    container_name: proxy_to_host
    command: tcp-listen:3000,fork,reuseaddr tcp-connect:host.docker.internal:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"

  
  yasgui:
    image: erikap/yasgui:latest
    container_name: yasgui
    ports:
      - "8080:80"
    environment:
      - DEFAULT_SPARQL_ENDPOINT=http://localhost:7878/query